name: Actualizar catálogo

on:
  schedule:
    - cron: "0 * * * *"  # Cada hora. Puedes cambiarlo.
  workflow_dispatch:      # Permite ejecutarlo manualmente desde GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: Ejecutar script de actualización
      run: |
        python actualizar_catalogo.py

    - name: Hacer commit si hubo cambios
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add productos.json
        git commit -m "Actualización automática del catálogo" || echo "No hay cambios"
        git push
