name: Sync Google Drive

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y libheif1
          pip install pydrive2 pillow pillow-heif
      - name: Ejecutar script
        run: python actualiza_catalogo.py
