name: Sincroniza fotos desde Google Drive

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'  # Ejecuta cada 30 minutos (UTC)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instala dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crea archivo de credenciales
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          echo "$GDRIVE_CREDENTIALS" > credentials.json

      - name: Ejecuta el script de sincronización
        run: python actualiza_catalogo.py

