name: Actualizar catálogo desde Google Drive

on:
  schedule:
    - cron: "*/30 * * * *"  # Cada 30 minutos
  workflow_dispatch:        # Permitir ejecución manual

jobs:
  actualizar:
    runs-on: ubuntu-latest
    env:
      GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias del sistema
        run: sudo apt-get update && sudo apt-get install -y libheif1

      - name: Instalar dependencias de Python
        run: |
          pip install pillow pillow-heif pandas google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

      - name: Ejecutar script principal
        run: python sincroniza_actualiza_catalogo.py

      - name: Hacer commit si hay cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add fotos/ catalogo.xlsx productos.json || true
          git diff --cached --quiet || git commit -m "Actualización automática de catálogo y fotos"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
