name: Sync y Actualiza Catálogo

on:
  schedule:
    - cron: "*/30 * * * *"  # Cada 30 minutos
  workflow_dispatch:        # Permite ejecución manual

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Instalar dependencias del sistema
        run: sudo apt-get update && sudo apt-get install -y libheif1

      - name: Instalar dependencias de Python
        run: |
          pip install pandas openpyxl pillow pillow-heif \
                      google-api-python-client google-auth \
                      google-auth-oauthlib google-auth-httplib2

      - name: Ejecutar script de sincronización y actualización
        run: python sincroniza_actualiza_catalogo.py

      - name: Hacer commit si hubo cambios
        run: |
          git add fotos/ catalogo.xlsx productos.json || true
          git diff --cached --quiet || git commit -m "Actualización automática de catálogo y fotos"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

